export ALLOW_MISSING_DEPENDENCIES=true

export TW_DEFAULT_LANGUAGE="en"
export OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
export OF_SKIP_ORANGEFOX_PROCESS=1

export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
export OF_NO_TREBLE_COMPATIBILITY_CHECK=1

export FOX_USE_BASH_SHELL=1
export FOX_ASH_IS_BASH=1
export FOX_USE_NANO_EDITOR=1
export FOX_USE_TAR_BINARY=1
export FOX_USE_ZIP_BINARY=1
export FOX_USE_SED_BINARY=1
export FOX_USE_XZ_UTILS=1
export FOX_REPLACE_BUSYBOX_PS=1

export OF_SKIP_MULTIUSER_FOLDERS_BACKUP=1
export OF_QUICK_BACKUP_LIST="/boot;/data;/system;"

export LC_ALL="C"
export FOX_INSTALLER_DEBUG_MODE=1

export OF_MAINTAINER=KrutosX
export FOX_RECOVERY_INSTALL_PARTITION="/dev/block/platform/sprd-sdhci.3/by-name/RECOVERY"
export OF_FLASHLIGHT_ENABLE=0
export OF_DEVICE_WITHOUT_PERSIST=1
